In [1]:
import numpy as np

In [2]:
from intdielec.workflow.orient_eps import OrientEps

/opt/miniconda3/envs/leiden/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
task = OrientEps(work_dir=".", topo="interface.psf", coord="test.lammpstrj")

In [4]:
task.universe

<Universe with 387 atoms>

In [5]:
task.n_frames

10

In [6]:
surf_ids = np.array([np.arange(292, 308), np.arange(372, 388)])

In [7]:
task.run(bins=np.arange(5), surf_ids=surf_ids)

/opt/miniconda3/envs/leiden/lib/python3.9/multiprocessing/reduction.py:51: UserWarning: Reader has no dt information, set to 1.0 ps
  cls(buf, protocol).dump(obj)
/Users/jxzhu/workspace/software/m_MDAnalysis/package/MDAnalysis/analysis/base.py:438: UserWarning: Reader has no dt information, set to 1.0 ps
  self.times[i] = ts.time
/Users/jxzhu/workspace/software/m_MDAnalysis/package/MDAnalysis/analysis/base.py:438: UserWarning: Reader has no dt information, set to 1.0 ps
  self.times[i] = ts.time
/Users/jxzhu/workspace/software/m_MDAnalysis/package/MDAnalysis/analysis/base.py:438: UserWarning: Reader has no dt information, set to 1.0 ps
  self.times[i] = ts.time
/Users/jxzhu/workspace/software/m_MDAnalysis/package/MDAnalysis/analysis/base.py:438: UserWarning: Reader has no dt information, set to 1.0 ps
  self.times[i] = ts.time
/Users/jxzhu/workspace/software/m_MDAnalysis/package/MDAnalysis/analysis/base.py:438: UserWarning: Reader has no dt information, set to 1.0 ps
  self.times[i] = 

In [8]:
import h5py

In [9]:
with h5py.File("eps_data.hdf5", "r") as f:
    print(f)
    for n in f:
        print(n)
    print(f["00"])
    for data in f["00"]:
        print(data)
        print(f["00"][data][...])
    # print(f[-1])

<HDF5 file "eps_data.hdf5" (mode r)>
00
01
<HDF5 group "/00" (6 members)>
M
5.925663986877427
M2
35.2475466827284
bins
[0 1 2 3 4]
inveps
[1.         1.         0.71237389 0.17357373]
m
[ 0.          0.         -0.00027608  0.00292033]
mM
[ 0.          0.         -0.00158228  0.01745917]


In [ ]:
import MDAnalysis as mda
fname_topo = "interface.psf"
fname_coord = "test.lammpstrj"
u = mda.Universe(fname_topo, fname_coord, topology_format="PSF", format="LAMMPSDUMP")
u._trajectory.n_frames